FROM python:3.9-slim
WORKDIR /app
COPY .env .
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY streamlit_app.py ./
CMD ["streamlit", "run", "streamlit_app.py", "--server.port", "8501", "--server.address", "0.0.0.0"]
