--
-- PostgreSQL database dump
--

\restrict sBoxG5VVpsY1jon9IZYHIHij8257fVr2ijGolIrf5YaBqFJEDRuXUueTVa4irfa

-- Dumped from database version 17.5 (aa1f746)
-- Dumped by pg_dump version 17.6 (Debian 17.6-2.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

-- *not* creating schema, since initdb creates it


--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS '';


--
-- Name: apply_daily_deals(integer, date, numeric, numeric); Type: PROCEDURE; Schema: public; Owner: -
--

CREATE PROCEDURE public.apply_daily_deals(IN cart_id integer, IN o_date date, IN minimum_price numeric, INOUT total numeric)
    LANGUAGE plpgsql
    AS $$
DECLARE
    this_product RECORD;
    discount_percent NUMERIC := 0;
    item_price NUMERIC;
    item_discount NUMERIC;
BEGIN
    FOR this_product IN
        SELECT * FROM cart_items WHERE cart_id = cart_id
    LOOP
        BEGIN
            SELECT discount INTO discount_percent
            FROM daily_deals
            WHERE p_id = this_product.p_id
              AND deal_date = o_date;
        EXCEPTION
            WHEN no_data_found THEN
                discount_percent := 0;
        END;

        SELECT price INTO item_price
        FROM product
        WHERE p_id = this_product.p_id;

        FOR i IN 1..this_product.qty LOOP
            item_discount := (discount_percent / 100.0) * item_price;
            total := total - item_discount;
        END LOOP;

        IF total < minimum_price THEN
            total := minimum_price;
        END IF;
    END LOOP;
END;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: buyer; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.buyer (
    buyer_id character varying(40)
);


--
-- Name: carrier; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.carrier (
    carrier_id integer NOT NULL,
    carrier_name character varying(30)
);


--
-- Name: carrier_carrier_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.carrier ALTER COLUMN carrier_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carrier_carrier_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cart; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cart (
    cart_id integer NOT NULL,
    buyer_id character varying(40),
    total_qty integer DEFAULT 0 NOT NULL,
    total_price double precision DEFAULT 0 NOT NULL,
    CONSTRAINT cart_total_qty_check CHECK ((total_qty >= 0))
);


--
-- Name: cart_cart_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cart ALTER COLUMN cart_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cart_cart_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cart_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cart_items (
    cart_id integer NOT NULL,
    p_id character varying(10),
    qty integer DEFAULT 1 NOT NULL,
    CONSTRAINT cart_items_qty_check CHECK ((qty >= 0))
);


--
-- Name: category; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.category (
    category_id integer NOT NULL,
    name character varying(30),
    c_desc character varying(20)
);


--
-- Name: category_category_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.category ALTER COLUMN category_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.category_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customer; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.customer (
    c_id character varying(40),
    fname character varying(200),
    lname character varying(30),
    phone character(10),
    email character varying(250),
    pwd character varying(60)
);


--
-- Name: customer_payment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.customer_payment (
    payment_id integer NOT NULL,
    c_id character varying(40),
    is_default character(1) DEFAULT '0'::bpchar,
    CONSTRAINT customer_payment_is_default_check CHECK ((is_default = ANY (ARRAY['0'::bpchar, '1'::bpchar])))
);


--
-- Name: customer_shipping; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.customer_shipping (
    address_id integer NOT NULL,
    c_id character varying(40),
    is_default character(1) DEFAULT '0'::bpchar,
    CONSTRAINT customer_shipping_is_default_check CHECK ((is_default = ANY (ARRAY['0'::bpchar, '1'::bpchar])))
);


--
-- Name: daily_deals; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.daily_deals (
    p_id character varying(10),
    deal_date date NOT NULL,
    discount numeric NOT NULL
);


--
-- Name: discount; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.discount (
    discount_id integer NOT NULL,
    discount_name character varying(20),
    d_desc character varying(100),
    discount_amt numeric NOT NULL,
    CONSTRAINT discount_discount_amt_check CHECK ((discount_amt >= (0)::numeric))
);


--
-- Name: discount_discount_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.discount ALTER COLUMN discount_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.discount_discount_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.orders (
    order_id integer NOT NULL,
    buyer_id character varying(40),
    discount_id integer,
    payment_id integer,
    order_date date NOT NULL
);


--
-- Name: orders_order_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.orders ALTER COLUMN order_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payment_details; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payment_details (
    payment_id integer NOT NULL,
    card_no bigint NOT NULL,
    cvv smallint NOT NULL,
    expiry_date date NOT NULL,
    billing_address character varying(500)
);


--
-- Name: payment_details_payment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payment_details ALTER COLUMN payment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_details_payment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product (
    p_id character varying(10),
    p_name character varying(1000),
    p_desc character varying(5000),
    price numeric NOT NULL,
    qty integer DEFAULT 0 NOT NULL,
    category_id integer,
    CONSTRAINT product_qty_check CHECK ((qty >= 0))
);


--
-- Name: product_images; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_images (
    p_id character varying(10),
    p_image character varying(100)
);


--
-- Name: product_reviews; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_reviews (
    p_id character varying(10),
    review_id integer NOT NULL
);


--
-- Name: returns; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.returns (
    return_id integer NOT NULL,
    buyer_id character varying(40),
    p_id character varying(10),
    order_id integer
);


--
-- Name: returns_return_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.returns ALTER COLUMN return_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.returns_return_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: review; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.review (
    review_id integer NOT NULL,
    buyer_id character varying(40),
    r_desc character varying(20000),
    title character varying(300),
    rating integer,
    seller_product_flag character(1),
    CONSTRAINT review_rating_check CHECK (((rating >= 1) AND (rating <= 5))),
    CONSTRAINT review_seller_product_flag_check CHECK ((seller_product_flag = ANY (ARRAY['S'::bpchar, 'P'::bpchar])))
);


--
-- Name: review_images; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.review_images (
    review_id integer NOT NULL,
    review_img character varying(200)
);


--
-- Name: review_review_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.review ALTER COLUMN review_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.review_review_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: seller; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.seller (
    seller_id character varying(40),
    seller_type character varying(100)
);


--
-- Name: seller_products; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.seller_products (
    seller_id character varying(40),
    p_id character varying(10)
);


--
-- Name: seller_reviews; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.seller_reviews (
    seller_id character varying(40),
    review_id integer NOT NULL
);


--
-- Name: shipment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.shipment (
    shipping_id integer NOT NULL,
    order_id integer,
    p_id character varying(10),
    carrier_id integer,
    shipment_type character(2) DEFAULT 'NP'::bpchar,
    status character varying(10),
    est_delivery_date date,
    actual_delivery_date date,
    CONSTRAINT shipment_shipment_type_check CHECK ((shipment_type = ANY (ARRAY['PP'::bpchar, 'NP'::bpchar])))
);


--
-- Name: shipment_shipping_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.shipment ALTER COLUMN shipping_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shipment_shipping_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shipping_details; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.shipping_details (
    address_id integer NOT NULL,
    street_address character varying(100),
    city character varying(100),
    state character varying(100),
    zip character varying(10),
    country character varying(60),
    phone character(10)
);


--
-- Name: shipping_details_address_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.shipping_details ALTER COLUMN address_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shipping_details_address_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: subscription; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.subscription (
    subscription_id integer NOT NULL,
    c_id character varying(40),
    start_date date NOT NULL,
    end_date date NOT NULL
);


--
-- Name: subscription_subscription_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.subscription ALTER COLUMN subscription_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subscription_subscription_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wishlist_item; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.wishlist_item (
    product_id character varying(10),
    buyer_id character varying(40)
);


--
-- Name: buyer buyer_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.buyer
    ADD CONSTRAINT buyer_pkey PRIMARY KEY (buyer_id);


--
-- Name: carrier carrier_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carrier
    ADD CONSTRAINT carrier_pkey PRIMARY KEY (carrier_id);


--
-- Name: cart_items cart_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT cart_items_pkey PRIMARY KEY (cart_id, p_id);


--
-- Name: cart cart_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart
    ADD CONSTRAINT cart_pkey PRIMARY KEY (cart_id);


--
-- Name: category category_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.category
    ADD CONSTRAINT category_pkey PRIMARY KEY (category_id);


--
-- Name: customer customer_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer
    ADD CONSTRAINT customer_email_key UNIQUE (email);


--
-- Name: customer_payment customer_payment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_payment
    ADD CONSTRAINT customer_payment_pkey PRIMARY KEY (c_id, payment_id);


--
-- Name: customer customer_phone_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer
    ADD CONSTRAINT customer_phone_key UNIQUE (phone);


--
-- Name: customer customer_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer
    ADD CONSTRAINT customer_pkey PRIMARY KEY (c_id);


--
-- Name: customer_shipping customer_shipping_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_shipping
    ADD CONSTRAINT customer_shipping_pkey PRIMARY KEY (address_id, c_id);


--
-- Name: daily_deals daily_deals_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.daily_deals
    ADD CONSTRAINT daily_deals_pkey PRIMARY KEY (p_id, deal_date);


--
-- Name: discount discount_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.discount
    ADD CONSTRAINT discount_pkey PRIMARY KEY (discount_id);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (order_id);


--
-- Name: payment_details payment_details_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_details
    ADD CONSTRAINT payment_details_pkey PRIMARY KEY (payment_id);


--
-- Name: product_images product_images_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_images
    ADD CONSTRAINT product_images_pkey PRIMARY KEY (p_id, p_image);


--
-- Name: product product_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT product_pkey PRIMARY KEY (p_id);


--
-- Name: product_reviews product_reviews_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_reviews
    ADD CONSTRAINT product_reviews_pkey PRIMARY KEY (p_id, review_id);


--
-- Name: returns returns_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.returns
    ADD CONSTRAINT returns_pkey PRIMARY KEY (return_id);


--
-- Name: review_images review_images_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review_images
    ADD CONSTRAINT review_images_pkey PRIMARY KEY (review_id, review_img);


--
-- Name: review review_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT review_pkey PRIMARY KEY (review_id);


--
-- Name: seller seller_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seller
    ADD CONSTRAINT seller_pkey PRIMARY KEY (seller_id);


--
-- Name: seller_products seller_products_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seller_products
    ADD CONSTRAINT seller_products_pkey PRIMARY KEY (seller_id, p_id);


--
-- Name: seller_reviews seller_reviews_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seller_reviews
    ADD CONSTRAINT seller_reviews_pkey PRIMARY KEY (seller_id, review_id);


--
-- Name: shipment shipment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shipment
    ADD CONSTRAINT shipment_pkey PRIMARY KEY (shipping_id);


--
-- Name: shipping_details shipping_details_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shipping_details
    ADD CONSTRAINT shipping_details_pkey PRIMARY KEY (address_id);


--
-- Name: subscription subscription_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subscription
    ADD CONSTRAINT subscription_pkey PRIMARY KEY (subscription_id);


--
-- Name: wishlist_item wishlist_item_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wishlist_item
    ADD CONSTRAINT wishlist_item_pkey PRIMARY KEY (product_id, buyer_id);


--
-- Name: buyer bbuyerfk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.buyer
    ADD CONSTRAINT bbuyerfk FOREIGN KEY (buyer_id) REFERENCES public.customer(c_id) ON DELETE CASCADE;


--
-- Name: cart cbuyerfk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart
    ADD CONSTRAINT cbuyerfk FOREIGN KEY (buyer_id) REFERENCES public.buyer(buyer_id) ON DELETE CASCADE;


--
-- Name: cart_items cicartfk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT cicartfk FOREIGN KEY (cart_id) REFERENCES public.cart(cart_id) ON DELETE CASCADE;


--
-- Name: cart_items ciproductfk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT ciproductfk FOREIGN KEY (p_id) REFERENCES public.product(p_id) ON DELETE CASCADE;


--
-- Name: customer_payment cpcustomerfk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_payment
    ADD CONSTRAINT cpcustomerfk FOREIGN KEY (c_id) REFERENCES public.customer(c_id) ON DELETE CASCADE;


--
-- Name: customer_payment cppaymentfk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_payment
    ADD CONSTRAINT cppaymentfk FOREIGN KEY (payment_id) REFERENCES public.payment_details(payment_id) ON DELETE CASCADE;


--
-- Name: customer_shipping csaddressfk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_shipping
    ADD CONSTRAINT csaddressfk FOREIGN KEY (address_id) REFERENCES public.shipping_details(address_id) ON DELETE CASCADE;


--
-- Name: customer_shipping cscustomerfk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_shipping
    ADD CONSTRAINT cscustomerfk FOREIGN KEY (c_id) REFERENCES public.customer(c_id) ON DELETE CASCADE;


--
-- Name: daily_deals ddproductfk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.daily_deals
    ADD CONSTRAINT ddproductfk FOREIGN KEY (p_id) REFERENCES public.product(p_id) ON DELETE CASCADE;


--
-- Name: orders obuyerfk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT obuyerfk FOREIGN KEY (buyer_id) REFERENCES public.buyer(buyer_id) ON DELETE SET NULL;


--
-- Name: orders odiscountfk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT odiscountfk FOREIGN KEY (discount_id) REFERENCES public.discount(discount_id) ON DELETE SET NULL;


--
-- Name: orders opaymentfk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT opaymentfk FOREIGN KEY (payment_id) REFERENCES public.payment_details(payment_id) ON DELETE SET NULL;


--
-- Name: product pcategoryfk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT pcategoryfk FOREIGN KEY (category_id) REFERENCES public.category(category_id) ON DELETE SET NULL;


--
-- Name: product_images piproductfk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_images
    ADD CONSTRAINT piproductfk FOREIGN KEY (p_id) REFERENCES public.product(p_id) ON DELETE CASCADE;


--
-- Name: product_reviews prproductfk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_reviews
    ADD CONSTRAINT prproductfk FOREIGN KEY (p_id) REFERENCES public.product(p_id) ON DELETE CASCADE;


--
-- Name: product_reviews prreviewfk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_reviews
    ADD CONSTRAINT prreviewfk FOREIGN KEY (review_id) REFERENCES public.review(review_id) ON DELETE CASCADE;


--
-- Name: review rbuyerfk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT rbuyerfk FOREIGN KEY (buyer_id) REFERENCES public.buyer(buyer_id) ON DELETE SET NULL;


--
-- Name: returns retbuyerfk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.returns
    ADD CONSTRAINT retbuyerfk FOREIGN KEY (buyer_id) REFERENCES public.buyer(buyer_id) ON DELETE SET NULL;


--
-- Name: returns retorderfk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.returns
    ADD CONSTRAINT retorderfk FOREIGN KEY (order_id) REFERENCES public.orders(order_id) ON DELETE SET NULL;


--
-- Name: returns retproductfk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.returns
    ADD CONSTRAINT retproductfk FOREIGN KEY (p_id) REFERENCES public.product(p_id) ON DELETE SET NULL;


--
-- Name: review_images rireviewfk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review_images
    ADD CONSTRAINT rireviewfk FOREIGN KEY (review_id) REFERENCES public.review(review_id) ON DELETE CASCADE;


--
-- Name: shipment scarrierfk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shipment
    ADD CONSTRAINT scarrierfk FOREIGN KEY (carrier_id) REFERENCES public.carrier(carrier_id) ON DELETE SET NULL;


--
-- Name: subscription scustomerfk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subscription
    ADD CONSTRAINT scustomerfk FOREIGN KEY (c_id) REFERENCES public.customer(c_id) ON DELETE SET NULL;


--
-- Name: shipment sorderfk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shipment
    ADD CONSTRAINT sorderfk FOREIGN KEY (order_id) REFERENCES public.orders(order_id) ON DELETE SET NULL;


--
-- Name: seller_products spproductfk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seller_products
    ADD CONSTRAINT spproductfk FOREIGN KEY (p_id) REFERENCES public.product(p_id) ON DELETE CASCADE;


--
-- Name: shipment sproductfk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shipment
    ADD CONSTRAINT sproductfk FOREIGN KEY (p_id) REFERENCES public.product(p_id) ON DELETE SET NULL;


--
-- Name: seller_products spsellerfk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seller_products
    ADD CONSTRAINT spsellerfk FOREIGN KEY (seller_id) REFERENCES public.seller(seller_id) ON DELETE CASCADE;


--
-- Name: seller_reviews srreviewfk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seller_reviews
    ADD CONSTRAINT srreviewfk FOREIGN KEY (review_id) REFERENCES public.review(review_id) ON DELETE CASCADE;


--
-- Name: seller_reviews srsellerfk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seller_reviews
    ADD CONSTRAINT srsellerfk FOREIGN KEY (seller_id) REFERENCES public.seller(seller_id) ON DELETE CASCADE;


--
-- Name: seller ssellerfk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seller
    ADD CONSTRAINT ssellerfk FOREIGN KEY (seller_id) REFERENCES public.customer(c_id) ON DELETE CASCADE;


--
-- Name: wishlist_item wibuyerfk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wishlist_item
    ADD CONSTRAINT wibuyerfk FOREIGN KEY (buyer_id) REFERENCES public.buyer(buyer_id) ON DELETE CASCADE;


--
-- Name: wishlist_item wiproductfk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wishlist_item
    ADD CONSTRAINT wiproductfk FOREIGN KEY (product_id) REFERENCES public.product(p_id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict sBoxG5VVpsY1jon9IZYHIHij8257fVr2ijGolIrf5YaBqFJEDRuXUueTVa4irfa

